# documentation
# https://docs.github.com/fr/code-security/dependabot/dependabot-security-updates/configuring-dependabot-security-updates
# https://docs.github.com/fr/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "github-actions"
      include: "scope"
    labels:
      - "CI"