# using https://github.com/haskell/actions
on: [push]
name: build
jobs:
  build:
    name: Haskell GHC ${{ matrix.ghc }} sample
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['9.2.5']
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3
      - name: setup haskell
        uses: haskell/actions/setup@v2
        with:
          ghc-version: ${{ matrix.ghc }}
          enable-stack: true
          stack-version: 'latest'
      - run: runhaskell Hello.hs