# documentation
# https://github.com/haskell/actions
# https://kodimensional.dev/github-actions

# uses
# - actions/checkout (3)
#     https://github.com/marketplace/actions/checkout
# - actions/cache (3)
#     https://github.com/marketplace/actions/cache
# - haskell/actions/setup (2)
#     https://github.com/haskell/actions

# TODO: add artifact release

name: CI

# run when push on main
on:
  push:
    branches: [master]

jobs:
  build:
    name: build-${{ matrix.ghc }}-${{ matrix.stack }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['9.2.5']
        stack: ['2.9.1']
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - uses: haskell/actions/setup@v2
      name: stack setup
      with:
        ghc-version: ${{ matrix.ghc }}
        enable-stack: true
        stack-version: ${{ matrix.stack }}
    - uses: actions/cache@v3
      name: cache ~/.stack
      with:
        path: ~/.stack
        key: stack-${{ matrix.ghc }}-${{ matrix.stack }}-${{ runner.os }}
    - name: install dependencies
      run: |
        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks --only-dependencies
    - name: build
      run: |
        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks
    - name: test
      run: |
        stack test --system-ghc

