# documentation
# https://github.com/haskell/actions
# https://kodimensional.dev/github-actions

# uses
# - actions/checkout (3)
#     https://github.com/marketplace/actions/checkout
# - actions/cache (3)
#     https://github.com/marketplace/actions/cache
# - haskell/actions/setup (2)
#     https://github.com/haskell/actions
# - softprops/action-gh-release (1)
#     https://github.com/softprops/action-gh-release

# TODO: check and add caching if needed
# TODO: add artifact release
# TODO: automatize setting program & version
# TODO: use variable for LTS

# Note: zip is removed for linux and macOS
# if needed this can be added
# zip -j  ${{ env.archive }}.zip       ${{ env.bin_path }}/${{ env.program }}

name: CI

# run when push on main
on:
  push:
    branches: [master]
env:
  lts: 20.5
  program: template-haskell-project-exe
  version: 0.1.3.0
  api_key: HsbREGVwE2R42Qq3CA1p3SYI/CCiEj6DLKww+yBKM2MQpa2RKu5igGTz5I3k1S5O85KEFhBTDm6uZ/ZNZS3/zuH813amUFmN6H269Bacypfrevb3TgLxT2VoxWNL3s4pklaD31zvX2g+0GPXgeVmx70Z/aeZKghXeFpwH22S/gtQqlWldQU+5Z7w1YFf74KN9JwKVjtClgewIYhtujD4Hki8QmJqKiOtr5eNHD7ATYSOtSSqk384qPbDKuJGjzESEbyZqZpgWCHCOA7NMWqMlM18LGFdQJGE6exN14iQMpM12g7ErIP+ss051FZsiusf7WNqoVGbuI5DsBVB8eb+5MJTryyfygFpM2H+ExtXx8nPAam/ygp32m4uPsjEbhw20oOplBDcx9oOnuWACwQNO5K0Gh0TCb7UH6he0yq2kP74potwAqhFiCkAP9mNmnX+l93Q7iZ/RrN8jw6M04uZqMrxi3NUGUy0cqgq7w+r/uFcdSLr464momgSqbtO5+Xf++YK1e9hqEqOQl9YUWadQkgWpa6/qwQB54ZLvYadUYqSvZqSkZnFamieziNVUPg8m9EPhLZJyEPATVkZbVIzaJvBh80ft67sfIk/+/7MCJBXvwj7+xK3ZaAVGjQFEnX2V55PfOXc+lGN08tr+0HRNf/XaxMI2+wT9gJX4ycxTIM=
jobs:
  build:
    name: build-${{ matrix.ghc }}-${{ matrix.stack }}-${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        ghc: ['9.2.5']
        stack: ['2.9.1']
        os: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
    - uses: actions/checkout@v3
    - name: stack setup
      uses: haskell/actions/setup@v2
      with:
        ghc-version: ${{ matrix.ghc }}
        enable-stack: true
        stack-version: ${{ matrix.stack }}
    #
    # caches
    #
    - name: cache ~/.stack (linux and macOS)
      uses: actions/cache@v3
      if: startsWith(matrix.os, 'windows') != true
      with:
        path: ~/.stack
        key: stack-${{ matrix.ghc }}-${{ matrix.stack }}-${{ env.lts }}-${{ runner.os }}
    - name: cache C:\sr\snapshots (windows x86)
      uses: actions/cache@v3
      if: startsWith(matrix.os, 'windows')
      with:
        path: C:\sr\snapshots
        key: stack-${{ matrix.ghc }}-${{ matrix.stack }}-${{ env.lts }}-${{ runner.os }}
    #
    # building & testing
    #
    - name: install dependencies
      run: |
        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks --only-dependencies
    - name: build
      run: |
        stack build --system-ghc --test --bench --no-run-tests --no-run-benchmarks
    - name: test
      run: |
        stack test --system-ghc
    #
    # setting os, arch, and bin_path
    #
    - name: set variables (linux x86)
      if: startsWith(matrix.os, 'ubuntu')
      run: |
        echo os=linux >> $GITHUB_ENV
        echo arch="x86_64" >> $GITHUB_ENV
        echo bin_path=`stack path --system-ghc --local-install-root`/bin >> $GITHUB_ENV
    - name: set variables (mac x86)
      if: startsWith(matrix.os, 'macOS')
      run: |
        echo os=osx >> $GITHUB_ENV
        echo arch="x86_64" >> $GITHUB_ENV
        echo bin_path=`stack path --system-ghc --local-install-root`/bin >> $GITHUB_ENV
    - name: set variables (windows)
      if: startsWith(matrix.os, 'windows')
      run: |
        echo "os=windows" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        echo "arch=x86_64" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
        $pwsh_bin_path = Join-Path (& stack path --system-ghc --local-install-root) bin
        echo "bin_path=$pwsh_bin_path" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
      shell: pwsh
    #
    # setting archive name
    #
    - name: set archive name (linux and macOS)
      if: startsWith(matrix.os, 'windows') != true
      run: |
        echo "archive=${{ env.program }}-${{ env.version }}-${{ env.os }}.${{ env.arch }}" >> $GITHUB_ENV
    - name: set archive name (windows)
      if: startsWith(matrix.os, 'windows')
      run: |
        $pwsh_archive = $Env:program+"-"+$Env:version+"-"+$Env:os+"."+$Env:arch
        echo "archive=$pwsh_archive" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
      shell: pwsh
    #
    # make archives
    #
    - name: make archive (linux and macOS)
      if: startsWith(matrix.os, 'windows') != true
      run: |
        tar czf ${{ env.archive }}.tar.gz -C ${{ env.bin_path }} ${{ env.program }}
        echo archive ${{ env.archive }}.tar.gz created in ${{ env.bin_path }} from ${{ env.bin_path }}/${{ env.program }}
        echo "archive_path=${{ env.bin_path }}/${{ env.archive }}.tar.gz" >> $GITHUB_ENV
    - name: make archive (windows)
      if: startsWith(matrix.os, 'windows')
      run: |
        $file = Join-Path $Env:bin_path $Env:program+".exe"
        $pwsh_archive_path = Join-Path $Env:bin_path $Env:archive+".zip"
        Get-ChildItem $file | Compress-Archive -DestinationPath $pwsh_archive_path
        echo archive $Env:archive+".zip" created in $Env:bin_path from $file
        echo "archive_path=$pwsh_archive_path" | Out-File -FilePath $Env:GITHUB_ENV -Encoding utf8 -Append
    #
    # release (if on a tag)
    #
    - name: release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        # tag_name: defaults to github.ref
        # name: defaults to tag name
        append_body: true
        # token: defaults to ${{ github.token }}
        files: |
          ${{ env.archive_path }}
